### PR TITLE
Update to support Sphinx 1.5+ versions

### PR DESCRIPTION
**Pull request by Lnaden**
This is to start the fix for pandegroup/openmm#2048 

@rmcgibbo I'll need you to cut version 0.3 and upload to pip so I can then update the meta.yaml file in the the Omnia conda-recipes. I tested this and it works backwards compatible with Sphinx 1.3.1 as well.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Sounds good.

**Comment by rmcgibbo** [comment]
I don't have my pypi credential on me right now (i'm currently at work, it's saved on home laptop) but i'll do a release when i get home.

**Comment by Lnaden** [comment]
Thanks! Once its on pip, just ping here and I'll take care of the rest.

**Comment by rmcgibbo** [comment]
I just did a release and pushed 0.3 to pypi.

**Comment by Lnaden** [comment]
Great! I have the PR on conda-recipes open and should be able to take care of everything from here. 

Thanks for the quick turnaround on this!

**Pull request merged**
